name: CI / Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/wisecow

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image tag
        id: tag
        run: |
          echo "tag=sha-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ steps.tag.outputs.tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ secrets.KUBECONFIG != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: '1.28.0'

      - name: Create kubeconfig file
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl version --client
      - name: Apply namespace and manifests
        env:
          IMAGE_TAG: ${{ steps.build-and-push.outputs.image-tag }}
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f k8s/namespace.yaml
          # Update image (immutable tag) then apply other manifests
          kubectl -n wisecow set image deployment/wisecow wisecow=${{ env.IMAGE }}:sha-${GITHUB_SHA::8} || true
          kubectl apply -f k8s/
          kubectl -n wisecow rollout status deployment/wisecow --timeout=120s || true
